export const WS_DOMAIN = 'ws://team-up.online'
export const HOST_DOMAIN = 'https://team-up.online'
export const PREFIX = '/api'
// export const WS_DOMAIN = 'ws://localhost:8080'
// export const HOST_DOMAIN = 'http://localhost:8080'
// export const PREFIX = ''