name: CI/CD

on:
  push:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: yarn install

      - name: Build_dev
        if: ${{ contains(github.ref, 'develop') && contains(github.event_name, 'push') }}
        run: REACT_APP_ENV=dev yarn build:react

      - name: Build_prod
        if: ${{ contains(github.ref, 'master') && contains(github.event_name, 'push') }}
        run: REACT_APP_ENV=prod yarn build:react

      - uses: actions/upload-artifact@master
        with:
          name: uploaded_files
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'develop') && contains(github.event_name, 'push')
    needs: build
    steps:
      - uses: actions/download-artifact@master
        with:
          name: uploaded_files
          path: ./build

      - name: copy file via ssh password
        if: ${{ contains(github.ref, 'develop') && contains(github.event_name, 'push') }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: "build/*"
          target: "/var/www/dev.team-up.online/html/hhton"
          strip_components: 1

      - name: copy file via ssh password
        if: ${{ contains(github.ref, 'develop') && contains(github.event_name, 'push') }}
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          port: 22
          source: "build/*"
          target: "/var/www/team-up.online/html/hhton"
          strip_components: 1